# Generated by Django 4.0.2 on 2022-02-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_use', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone1',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='phone2',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signature_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='total_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='comments',
            field=models.TextField(blank=True, max_length=500000),
        ),
    ]
