# Generated by Django 4.0.2 on 2022-02-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_use', '0004_alter_client_responsible_alter_event_responsible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='event',
            name='responsible',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
