# Generated by Django 4.0.2 on 2022-02-23 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_use', '0005_remove_event_contract_remove_event_responsible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(null=True)),
                ('signed', models.BooleanField(default=False)),
                ('signature_date', models.DateTimeField(null=True)),
                ('total_amount', models.PositiveBigIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_use.client')),
            ],
        ),
    ]
