# Generated by Django 4.0.2 on 2022-03-02 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_use', '0005_remove_event_contract_remove_event_responsible_and_more'),
        ('api_contract', '0002_alter_contract_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api_use.client'),
        ),
    ]
