# Generated by Django 4.0.2 on 2022-02-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_delete_commercialteam_delete_managementteam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assignement',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Support', 'Support'), ('Management', 'Management')], max_length=64),
        ),
    ]
