# Generated by Django 4.0.2 on 2022-02-14 10:43

import connection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_alter_user_assignement'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', connection.models.MyUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='user',
            name='update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
