# Generated by Django 4.0.2 on 2022-02-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0005_managementteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagementTeam',
        ),
    ]
