# Generated by Django 4.0.2 on 2022-02-23 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('UP', 'Upcoming'), ('DONE', 'Finished')], default='Upcoming', max_length=64)),
                ('comments', models.TextField(blank=True, max_length=500000)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_contract.contract')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
